version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: diploma_app
    restart: unless-stopped
    ports:
      - "6969:6969"
    environment:
      - SPRING_APPLICATION_NAME=diploma
      - SERVER_PORT=6969
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/rollerblind
    depends_on:
      - mongo

volumes:
  mongo-data:
